name: Publish docker images
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build & Publish Image
        working-directory: ./
        run: |
          docker login -u ursnj -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build -t ursnj/nayanui:latest .
          docker push ursnj/nayanui:latest
